baseurl: http://the-baguettes.github.io
canonifyurls: true
languageCode: en-us
title: The Baguettes

params:
    github: The-Baguettes

menu:
    main:
        - name: Home
          url: /
          identifier: home
          weight: -1

        - name: About
          url: /about
          identifier: about

        - name: TFBS
          url: /tfbs
          identifier: TFBS
